/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSuperRouteImport } from './routes/app.super'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReservationsRouteImport } from './routes/app.reservations'
import { Route as AppReadersRouteImport } from './routes/app.readers'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppInboxRouteImport } from './routes/app.inbox'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppBorrowRouteImport } from './routes/app.borrow'
import { Route as AppAiRouteImport } from './routes/app.ai'
import { Route as AppBorrowIndexRouteImport } from './routes/app.borrow.index'
import { Route as AppBorrowEditRouteImport } from './routes/app.borrow.edit'
import { Route as AppBorrowAddRouteImport } from './routes/app.borrow.add'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperRoute = AppSuperRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReservationsRoute = AppReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AppRoute,
} as any)
const AppReadersRoute = AppReadersRouteImport.update({
  id: '/readers',
  path: '/readers',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBorrowRoute = AppBorrowRouteImport.update({
  id: '/borrow',
  path: '/borrow',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppBorrowIndexRoute = AppBorrowIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBorrowRoute,
} as any)
const AppBorrowEditRoute = AppBorrowEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppBorrowRoute,
} as any)
const AppBorrowAddRoute = AppBorrowAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppBorrowRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/app/ai': typeof AppAiRoute
  '/app/borrow': typeof AppBorrowRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/history': typeof AppHistoryRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/readers': typeof AppReadersRoute
  '/app/reservations': typeof AppReservationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/super': typeof AppSuperRoute
  '/app/': typeof AppIndexRoute
  '/app/borrow/add': typeof AppBorrowAddRoute
  '/app/borrow/edit': typeof AppBorrowEditRoute
  '/app/borrow/': typeof AppBorrowIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/app/ai': typeof AppAiRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/history': typeof AppHistoryRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/readers': typeof AppReadersRoute
  '/app/reservations': typeof AppReservationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/super': typeof AppSuperRoute
  '/app': typeof AppIndexRoute
  '/app/borrow/add': typeof AppBorrowAddRoute
  '/app/borrow/edit': typeof AppBorrowEditRoute
  '/app/borrow': typeof AppBorrowIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/app/ai': typeof AppAiRoute
  '/app/borrow': typeof AppBorrowRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/history': typeof AppHistoryRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/readers': typeof AppReadersRoute
  '/app/reservations': typeof AppReservationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/super': typeof AppSuperRoute
  '/app/': typeof AppIndexRoute
  '/app/borrow/add': typeof AppBorrowAddRoute
  '/app/borrow/edit': typeof AppBorrowEditRoute
  '/app/borrow/': typeof AppBorrowIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/contact'
    | '/login'
    | '/app/ai'
    | '/app/borrow'
    | '/app/dashboard'
    | '/app/history'
    | '/app/inbox'
    | '/app/notifications'
    | '/app/readers'
    | '/app/reservations'
    | '/app/settings'
    | '/app/super'
    | '/app/'
    | '/app/borrow/add'
    | '/app/borrow/edit'
    | '/app/borrow/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/app/ai'
    | '/app/dashboard'
    | '/app/history'
    | '/app/inbox'
    | '/app/notifications'
    | '/app/readers'
    | '/app/reservations'
    | '/app/settings'
    | '/app/super'
    | '/app'
    | '/app/borrow/add'
    | '/app/borrow/edit'
    | '/app/borrow'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/contact'
    | '/login'
    | '/app/ai'
    | '/app/borrow'
    | '/app/dashboard'
    | '/app/history'
    | '/app/inbox'
    | '/app/notifications'
    | '/app/readers'
    | '/app/reservations'
    | '/app/settings'
    | '/app/super'
    | '/app/'
    | '/app/borrow/add'
    | '/app/borrow/edit'
    | '/app/borrow/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/super': {
      id: '/app/super'
      path: '/super'
      fullPath: '/app/super'
      preLoaderRoute: typeof AppSuperRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reservations': {
      id: '/app/reservations'
      path: '/reservations'
      fullPath: '/app/reservations'
      preLoaderRoute: typeof AppReservationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/readers': {
      id: '/app/readers'
      path: '/readers'
      fullPath: '/app/readers'
      preLoaderRoute: typeof AppReadersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/borrow': {
      id: '/app/borrow'
      path: '/borrow'
      fullPath: '/app/borrow'
      preLoaderRoute: typeof AppBorrowRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai': {
      id: '/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/borrow/': {
      id: '/app/borrow/'
      path: '/'
      fullPath: '/app/borrow/'
      preLoaderRoute: typeof AppBorrowIndexRouteImport
      parentRoute: typeof AppBorrowRoute
    }
    '/app/borrow/edit': {
      id: '/app/borrow/edit'
      path: '/edit'
      fullPath: '/app/borrow/edit'
      preLoaderRoute: typeof AppBorrowEditRouteImport
      parentRoute: typeof AppBorrowRoute
    }
    '/app/borrow/add': {
      id: '/app/borrow/add'
      path: '/add'
      fullPath: '/app/borrow/add'
      preLoaderRoute: typeof AppBorrowAddRouteImport
      parentRoute: typeof AppBorrowRoute
    }
  }
}

interface AppBorrowRouteChildren {
  AppBorrowAddRoute: typeof AppBorrowAddRoute
  AppBorrowEditRoute: typeof AppBorrowEditRoute
  AppBorrowIndexRoute: typeof AppBorrowIndexRoute
}

const AppBorrowRouteChildren: AppBorrowRouteChildren = {
  AppBorrowAddRoute: AppBorrowAddRoute,
  AppBorrowEditRoute: AppBorrowEditRoute,
  AppBorrowIndexRoute: AppBorrowIndexRoute,
}

const AppBorrowRouteWithChildren = AppBorrowRoute._addFileChildren(
  AppBorrowRouteChildren,
)

interface AppRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppBorrowRoute: typeof AppBorrowRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppInboxRoute: typeof AppInboxRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppReadersRoute: typeof AppReadersRoute
  AppReservationsRoute: typeof AppReservationsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSuperRoute: typeof AppSuperRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppBorrowRoute: AppBorrowRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppInboxRoute: AppInboxRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppReadersRoute: AppReadersRoute,
  AppReservationsRoute: AppReservationsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSuperRoute: AppSuperRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
